Run PEP8 on content
Azure-Samples/storage-python-getting-started pull request #3
Opened 2019-06-20 00:06 UTC by sptramer

Hello! The Azure documentation team (Content & Learning) is updating existing
Python samples to conform to PEP8. This consists of (only) running `autopep8`
on content. Even if this PR contains only whitespace changes, please accept it.

If you have questions about the rationale behind this change, please email
Microsoft alias `sttramer`.

2019-06-27 18:54 UTC, lmazuel requested changes
Seems some copy/pasting issue

2019-06-27 18:54 UTC, lmazuel commented on AzureStoragePythonGettingStarted/Blobs.py
> +omcontainername(length):
Seems broken

2019-06-28 17:12 UTC, sptramer commented
@lmazuel Looks like the CI job is failing due to an auth issue - not related to the pep8 changes.

2019-07-01 19:32 UTC, lmazuel approved these changes

2019-07-01 19:32 UTC, merged